---

version: "3.7"

services:
  app:
    working_dir: /app
    tty: true
    image: my-debian:buster
    build:
      context: containers/client
      dockerfile: Dockerfile
    environment:
      ENV: $ENV
      SSHFS_USER: $SSHFS_USER
      SSHFS_PASSWORD: $SSHFS_PASSWORD
      SSHFS_DEVICE: $SSHFS_DEVICE
      SSHFS_POSITION: $SSHFS_POSITION
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - sshfsvolume-aaa:/app/hoge
