---

version: "3.7"

services:
  fake-storage:
    image: my-busybox
    build:
      context: containers/storage-server
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./fake-storage:/var/local/fake-storage

  app:
    working_dir: /app
    tty: true
    image: my-debian:buster
    build:
      context: containers/client
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      ENV: $ENV
      MOUNT_DEVICE: $MOUNT_DEVICE
      MOUNT_POSITION: $MOUNT_POSITION
      FILE_SYSTEM_TYPE: $FILE_SYSTEM_TYPE
    links:
      - fake-storage
